### ISSUE TITLE
Count response type is inconsistent from official Census by default

### ISSUE THREAD

**Issue by bigwoke** [PS2Sanctuary/Sanctuary.Census#5]
The `count` verb returns the count as a string value, while the official Census returns a number.

For example:
- Official `https://census.daybreakgames.com/s:example/count/ps2/zone` returns `{"count":14}`
- Sanctuary `https://census.lithafalcon.cc/s:example/count/ps2/zone` returns `{"count":"11"}`

Of course, using `c:censusJSON=false` works around this issue and brings Sanctuary in line with the official response, which follows JSON spec.

**Comment by carlst99** [comment]
Ah yeah, good point lol. One of those things I never solved in the initial rollout and has been woefully ignored ever since. Seen as this is now somewhat of a breaking change for Sanctuary.Census (not that I expect it would cause trouble for any consumers) I'll notify the community Discord channel with a week before implementing the change, starting from today.

**Comment by carlst99** [comment]
This change has now been deployed
